### ISSUE TITLE
Dropdown: items missing "key" prop, React warning displayed

### ISSUE THREAD

**Issue by mcrawshaw** [Semantic-Org/Semantic-UI-React#1710]
### Steps
 - Update from version 0.68.3 to 0.68.4.
 - Introduce a ```Dropdown``` element with more than one ```option``` specified.  ```selection``` needs to be specified also.
 - Run.

### Expected Result
No warning from React.

### Actual Result
React error:
``` Warning: Each child in an array or iterator should have a unique "key" props.  Check the render method of 'Dropdown'.```

### Version
0.68.4

**Comment by mcrawshaw** [comment]
Note, adding a ```key``` to each option fixes the issue.  For example:
```
<Dropdown selection options={[key: "1", value: "1", name: "Option 1"]} />
```
This wasn't the case for 0.68.3.  I see a reference to ```key``` in the docs, but it is not consistently specified in the examples.

**Comment by mcrawshaw** [comment]
Looks to be an intended change.  This issue is mentioned in the latest release documentation:
https://github.com/Semantic-Org/Semantic-UI-React/issues/1634

So does this mean we need ```key```, ```value```, and ```text``` now?

@karlludwigweise @davezuko

**Comment by dvdzkwsk** [comment]
From my understanding, `key` is definitely the _preferred_ way, but it should have been nearly backwards compatible due to [createShorthandFactory](https://github.com/Semantic-Org/Semantic-UI-React/blob/754416e7b37b260fcb625463afc6bcae5a41475e/src/lib/factories.js) using `value` as the default if no key exists.

@levithomason I am, however, curious about this line: https://github.com/Semantic-Org/Semantic-UI-React/blob/754416e7b37b260fcb625463afc6bcae5a41475e/src/lib/factories.js#L87. This looks to be checking the wrong value, at least from my initial read through of the code. Are we sure that `value` is being used correctly as the default? Maybe I missed something in the DropdownItem change?

**Comment by jhartma** [comment]
I have a small problem, though: react throws the unique key prop error when ```allowAdditions``` is defined and I am not sure how to add a key prop there. Seems like the ```Add``` entry has no key?

**Comment by karlludwigweise** [comment]
This is the reason I did not want to make the change myself. The Dropdown is too big of a component to oversee for a first time change; for me at least. The component should ideally generate its own keys and use those.

**Comment by mcrawshaw** [comment]
@karlludwigweise, no stress, we have a work around.

Let's see what @levithomason says about the factory before we continue.

**Comment by layershifter** [comment]
Here is problem with a factory.

It will generate key only when element passed to it as `number` or `string`. When element is passed as object, factory expects that user will define `key` himself.

I will make PR that fixes this.

**Comment by levithomason** [comment]
This is actually not a bug, if you pass a string/number primitive then we'll assume that as they key.  Otherwise, if you pass an options object or an element then you need to supply your own key just as is required by React itself.

@mcrawshaw
>So does this mean we need key, value, and text now?

Yep.  Anytime you use an object or an element in an array you'll need to pass a key.

If you use primitive shorthand (i.e. a string or number) then the shorthand factory will assume that value as the key.

@davezuko 
Factories do not use the `value` prop for keys, that is specific only to the [hidden `select`](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L1074) in the Dropdown.  Factories will only use `key`/`childKey` to generate keys, no more magic key generation business as we used to have.

Tangent: the hidden select arguably should go away entirely, it is an artifact from the old days.

@jhartma 
Thank you, this was an oversight on our part.  The [`addItem`](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L765) object itself does not have a `key`.  I've opened #1727 to resolve this issue.

**Comment by levithomason** [comment]
@jhartma fixed in https://github.com/Semantic-Org/Semantic-UI-React/pull/1727, it will go out on the next release.

**Comment by jhartma** [comment]
@levithomason nice, thanks a lot for the quick fix

**Comment by layershifter** [comment]
@levithomason it seems that you don't understand the problem described there. In #1639 we broken automatic `key` generation for `Dropdown.Item`.  After this change we always pass an object to the factory, as I said, I [proposed](https://github.com/Semantic-Org/Semantic-UI-React/issues/1720#issuecomment-305165602) there, if you check it's code you will better understand problem.

**Comment by levithomason** [comment]
@layershifter thanks for pointing out my oversight.  There are two points here:

1. Users' are now required to pass `key` in their `options`.  This is the intended usage and not a bug.  It should have been shipped as a breaking change but was not.

1. Rather than update the single case in the Dropdown to handle valid falsy `key` values, we should add the `isNil` check to the factory [here](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/factories.js#L80).  We currently check `if (!props.key) ....`, this treats falsy shorthand keys as nonexistent.

I'll update the PR you submitted to fix number 2 above.  This way, all keys in all components are fixed.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.68.5`.

**Comment by SidecarMaster** [comment]
The problem still exists. This is the array I passed in as options: 
```[{key: "react", value: "react", text: "react"}, {key: "redux", value: "redux", text: "redux"}, {key: "udacity", value: "udacity", text: "udacity"}```

This is my Dropdown code: 
```
        <Dropdown
          selection
          label={field.label}
          options={options}
          placeholder='Select Category'
          error={errorAttr}
          >
        </Dropdown>
```
And this is what is generated: 
```<div label="Select Category " role="listbox" aria-expanded="false" class="ui selection dropdown" tabindex="0"><div class="text" role="alert" aria-live="polite">react</div>...</div>```

As you can see in ```<div class="text" role="alert" aria-live="polite">react</div>``` It still doesn't have a key even if the object I passed in has a key property.

**Comment by levithomason** [comment]
Note, React doesn't render `key`s to the DOM.  They are used internally only.  This example works in docs and tests.  There must be something in the project using SUIR causing this.

If you create a minimal repo showing the issue, we can investigate further.

**Comment by rawberg** [comment]
Is there a way to specify a different object property as the key, such as the unique id that might be returned from the server? something like `key={id} or key={item.id}`

**Comment by levithomason** [comment]
@rawberg both `key` usages you've given are valid there.  Not sure of your implementation.  You might have better luck on Gitter or StackOverflow as this is a usage question.

**Comment by rawberg** [comment]
reading through the [source](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L1229) and #1720 it looks specifying a key no longer works.

**Comment by levithomason** [comment]
Keys in Dropdown options are still required and still work.  If you do not pass a `key` we will use the `value` as a fallback.
