### ISSUE TITLE
Tab menu option tabular is being overused for both style and position.

### ISSUE THREAD

**Issue by ryanmcgarvey** [Semantic-Org/Semantic-UI-React#2264]
### Steps
Given the following menu options for Tab:
```
const menu = {
  attached: false,
  fluid: true,
  vertical: true,
  tabular: 'right',
  secondary: true,
  borderless: true,
}
```
### Expected Result
The tabs should be on the right, and the style should be secondary (non-tabular).

### Actual Result
The tabs are on the right, but the style is tabular, ignoring the secondary configuration.

### Version
0.75.1

### Testcase
[Example](https://codesandbox.io/s/womxq04zp5)
[Proposed solution](https://codesandbox.io/s/0mm43m33xl)
In my PR #2265 - I've added an "aligned" option, which is used to determine right or left alignment, regardless of which style configuration you've set.

**Comment by ryanmcgarvey** [comment]
@brianespinosa How do I select my fork as a dependency? I've fixed the issue with pull request #2265 but don't know how to create w test case on the sandbox without pushing a new package up to npm.

**Comment by ryanmcgarvey** [comment]
@brianespinosa I created a fork on NPM, as seen here: https://codesandbox.io/s/0mm43m33xl

**Comment by brianespinosa** [comment]
@ryanmcgarvey I forked your pen here: https://codesandbox.io/s/kkklrvz9n5

The options for vertical type menus can be found here: https://semantic-ui.com/collections/menu.html#vertical-menu

In the pen I edited for you, I set your vertical menu to `secondary` instead of `tabular`. Keep in mind that for the `Tab` component, the `menu` prop is a shorthand for the `Menu` component itself so all available props for it can be seen in the docs I linked to above.

**Comment by ryanmcgarvey** [comment]
@brianespinosa the issue is that in order to right align the menu, tabular must be set to 'right', which then overrides the secondary option and sets the tab style.

**Comment by levithomason** [comment]
@ryanmcgarvey please fill out the complete issue template.  I'm still not able to understand the issue and proposed solution.  We want to help, we need the full information in order to do so effectively.  Thanks in advance.

**Comment by ryanmcgarvey** [comment]
@levithomason Updated issue as per the template. Thanks for being patient guys - I consume WAY more open source software than I contribute to. Let me know if you need any more clarification.

**Comment by levithomason** [comment]
@ryanmcgarvey thanks much! I immediately understood the issue now and I also agree with your proposal.
