### ISSUE TITLE
Popup: with hoverable stay open when cursor leaves the popup

### ISSUE THREAD

**Issue by InExtremaRes** [Semantic-Org/Semantic-UI-React#3508]
### Steps
1. Render a Popup with a Button as trigger and `hoverable`.
2. Hover the button to open the popup, then put the cursor inside the popup.
3. Let the cursor leave the popup.

### Expected Result
The popup should close since the cursor leave the popup.

### Actual Result
The popup keeps open.

### Version
0.86.0 (it works correctly in 0.85.0)

### Description
This only happens with `hoverable`. You can see the effect here:
![popup-1](https://user-images.githubusercontent.com/1635491/54482809-e25a3d80-4827-11e9-8381-546625fd0d49.gif)

When the cursor exit the popup it keeps open. In version 0.85 the popup was closed when the cursor exit the popup. The problem is more noticeable in this view with many buttons and popups:
![popup-2](https://user-images.githubusercontent.com/1635491/54482854-a07dc700-4828-11e9-8e47-7cd9b88f4138.gif)

**Comment by pratheekhegde** [comment]
This bug seems to be still present in 0.86.0

**Comment by layershifter** [comment]
It was fixed recently and was not released yet....

**Comment by martinop** [comment]
is this error fixed?

**Comment by layershifter** [comment]
Yep, it was released in `0.87.0`, https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md#v0870-2019-05-06

**Comment by martinop** [comment]
That version has a problem with the position of the Popup, do not respect it

**Comment by Aequitas737** [comment]
I'm still getting this with `0.88.2`. Possibly something to do with components next to each other in a table? If I add padding I don't get it as often (if I move the mouse quickly then I still do, but slowly is fine with some padding). Or due to being a button component?
