### ISSUE TITLE
React deprecation warning for Menu component

### ISSUE THREAD

**Issue by PawelJ-PL** [Semantic-Org/Semantic-UI-React#3757]
### Steps
Use `<Menu>` component

### Expected Result
No warning in JS console

### Actual Result
Following warning message in JS console:
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Menu
```

### Version
0.87.3

**Comment by Demintika** [comment]
There are a lot more deprecated lifecycles in React 16.9 that Semantic UI React still use.

**Comment by cassiopagnoncelli** [comment]
Just got

```
react-dom.development.js:12029 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Dropdown
```

Same issue for `Portal` and others.

**Comment by flppv** [comment]
Also got annoying warnings for `CardElement, Checkbox, Menu, Provider, Tab`

**Comment by rinkisingh8181** [comment]
Hey Guys,

What is the work around for these warnings?

**Comment by layershifter** [comment]
Fix was released in `0.88.0` few hours ago.

> Also got annoying warnings for `CardElement, Checkbox, Menu, Provider, Tab`

`CardElement`, `Provider` are not our components.

**Comment by Talkwondo** [comment]
Have this warning too now at "semantic-ui-react": "^0.88.2"

**Comment by AliTakrar** [comment]
"semantic-ui-react": "^0.88.2" has this warning with Menu ,  Button 
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: Menu

index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefFindNode which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in button (created by Button)
    in RefFindNode (created by Ref)
    in Ref (created by Button)
    in Button (at NavBar.tsx:17)
    in div (created by MenuItem)
    in MenuItem (at NavBar.tsx:16)
    in div (created by Container)
    in Container (at NavBar.tsx:10)
    in div (created by Menu)
    in Menu (at NavBar.tsx:9)
    in NavBar (at App.tsx:35)
    in div (at App.tsx:34)
    in App (at src/index.tsx:9)
    in StrictMode (at src/index.tsx:8)

**Comment by drewkill32** [comment]
Looks like it is still an issue or a new issue came up in "semantic-ui-react": "^0.88.2". can you open this back up?

**Comment by TemporalAgent7** [comment]
Still seeing these warnings in March 2021.
